# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DemoLists' do
pod 'GradientView', '~> 2.1.0'
#pod 'JSAnimatedImagesView', '~> 1.0.0'
end

